on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Get docker image version
          id: get_version
          run:  |
            MAJOR=$(cat VERSION | cut -d . -f 1)
            MINOR=$(cat VERSION | cut -d . -f 2)
            PATCH=$(cat VERSION | cut -d . -f 3)
            VERSION="v${MAJOR}.${MINOR}.${PATCH}"
            echo "::set-output name=version::${VERSION}"
#         - name: 'Build and push image'
#           uses: azure/docker-login@v1
#           with:
#             login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#             username: ${{ secrets.REGISTRY_USERNAME }}
#             password: ${{ secrets.REGISTRY_PASSWORD }}
#         - run: |
#             docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:v${{ steps.getversion.outputs.version }}
#             docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:v${{ steps.getversion.outputs.version }}
#         - name: 'Deploy to Azure Container Instances'
#           uses: 'azure/aci-deploy@v1'
#           with:
#             resource-group: ${{ secrets.RESOURCE_GROUP }}
#             dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
#             image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:v${{ steps.getversion.outputs.version }}
#             registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#             registry-username: ${{ secrets.REGISTRY_USERNAME }}
#             registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#             name: aci-sampleapp
#             location: 'central india'
